### PR TITLE
Remove createJSModules for RN 0.47.

### PR DESCRIPTION
**Pull request by exKAZUu**
Many react-native libraries removes this method (e.g. https://github.com/Microsoft/react-native-code-push/issues/894).

### CODE REVIEW

**Comment by Andruschenko** [comment]
Thanks for the PR @exKAZUu ! Will the code still be downards compatible to older RN versions after removing this overriding method?

**Comment by exKAZUu** [comment]
I think this PR breaks backward compatibility (e.g. RN 0.46 doesn't work on this).
Removing only the annotation (@Override) is perhaps able to keep the compatibility. I'll check it!

**Comment by exKAZUu** [comment]
I found we could keep the backward compatibility via https://github.com/Microsoft/react-native-code-push/pull/895#issuecomment-325700522 and https://github.com/Microsoft/react-native-code-push/pull/980, so I modified my PR.

**Comment by Andruschenko** [comment]
Excellent! Thank you! Could you please also add the comment `// Deprecated RN 0.47` as it was done [here](https://github.com/rebeccahughes/react-native-device-info/pull/191/files). Then it is visible to everyone.

After this change I'll accept your PR.

**Comment by exKAZUu** [comment]
Thank you for your feedback! I modified my PR.

**Comment by Andruschenko** [comment]
Thanks for the fix! I merged it and the new version 2.0.3 contains it.

**Comment by exKAZUu** [comment]
Thank you for the release! My team will use your library :)

**Pull request merged**
